/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conguencial_multiplicativo;

import java.math.BigDecimal;
import java.text.DecimalFormat;
//import javafx.scene.chart.Chart;

/**
 *
 * @author @Jonathan_Tillaguango_J
 */
public class GUITestPoker extends javax.swing.JFrame {

    /**
     * Creates new form GUITestPoker
     */
    public GUITestPoker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        txtDPoker = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSalidaPoker = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        cbPPoker = new javax.swing.JComboBox<>();
        btnCalcularPoker = new javax.swing.JButton();
        txtSemillaPoker = new javax.swing.JTextField();
        txtTPoker = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaData = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaFE = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("m:10 y d:");

        lblSalida.setText("SERIE");

        txtDPoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPokerActionPerformed(evt);
            }
        });

        textAreaSalidaPoker.setColumns(20);
        textAreaSalidaPoker.setRows(5);
        textAreaSalidaPoker.setEnabled(false);
        jScrollPane1.setViewportView(textAreaSalidaPoker);

        jLabel1.setText("Semilla (*no debe ser divisible entre 2 y 5 )");

        jLabel2.setText("Constante multiplicativa (a=200t±p)");

        jLabel3.setText("Modulo (patencia 10)");

        jLabel0.setText("Prueba del poker");

        cbPPoker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "7", "11", "13", "17", "19", "23", "29", "31", "37", "41", "43", "47", "53", "59", "61", "67", "71", "73", "79", "83", "89", "97" }));
        cbPPoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPPokerActionPerformed(evt);
            }
        });

        btnCalcularPoker.setText("Calcular");
        btnCalcularPoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPokerActionPerformed(evt);
            }
        });

        txtSemillaPoker.setToolTipText("");
        txtSemillaPoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemillaPokerActionPerformed(evt);
            }
        });

        txtTPoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPokerActionPerformed(evt);
            }
        });

        jLabel5.setText("p");

        jLabel4.setText("t:");

        textAreaData.setColumns(20);
        textAreaData.setRows(5);
        jScrollPane2.setViewportView(textAreaData);

        jLabel6.setText("Datos");

        textAreaFE.setColumns(20);
        textAreaFE.setRows(5);
        jScrollPane3.setViewportView(textAreaFE);

        jLabel9.setText("console");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnCalcularPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(txtTPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalida)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jLabel0))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSemillaPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbPPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(200, 200, 200)
                            .addComponent(jLabel8)))
                    .addContainerGap(339, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtDPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnCalcularPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalida)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtSemillaPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbPPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addGap(514, 514, 514)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDPokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPokerActionPerformed

    private void cbPPokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPPokerActionPerformed

    }//GEN-LAST:event_cbPPokerActionPerformed

    private void btnCalcularPokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPokerActionPerformed
        //variables para calcular la serie
        vista vista = new vista();
        Double seeb = Double.parseDouble(txtSemillaPoker.getText().toString());
        Double t = Double.parseDouble(txtTPoker.getText().toString());
        Double p = Double.parseDouble((String) cbPPoker.getSelectedItem().toString());
        int d = Integer.parseInt((String) txtDPoker.getText().toString());
        vista.cMultiplicativo(seeb, t, p, d);
        Double[] conMult = vista.cMultiplicativo(seeb, t, p, d);
        present(conMult);//se presenta la seri generada
        int longitude = conMult.length;
        pokerTest(conMult);
        //System.out.println("ssss " + longitude);

        //FIN
    }//GEN-LAST:event_btnCalcularPokerActionPerformed

    private void txtSemillaPokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemillaPokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemillaPokerActionPerformed

    private void txtTPokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTPokerActionPerformed
//Methods
    //Method for present

    public void present(Double[] serie) {
        String print = "";
        for (int i = 1; i <= serie.length; i++) {
            if (i == 1) {
                print += "n\t" + "Xn\n" + i + "\t" + serie[i - 1] + "\n";
                textAreaSalidaPoker.setText(print);
            } else {
                print += i + "\t" + serie[i - 1] + "\n";
                textAreaSalidaPoker.setText(print);
            }
        }

    }

    //Method for claculate the poker test
    public void pokerTest(Double[] serie) {
        //Types of poker
        final double allDiferent, aPair, twoPair, tercia, full, poker, quintilla;
        allDiferent = 0.30240;
        aPair = 0.50400;
        twoPair = 0.10800;
        tercia = 0.07200;
        poker = 0.00450;
        quintilla = 0.00010;
        //array to store values of the given array in values divided by 10^5(10^numbers of carts)\
        int n = serie.length;
        System.out.println("  h  " +n);
        int nCards = 5; //number of cards
        Double[] numbersFloat = new Double[n];//Decimal numbres
        Integer[] descompose = new Integer[n];//Array of Array
        //Fe
        int cont = 0;
        String print = "";
        String PrintTotal="";
        double number = 0;
        String str;
        Integer[] digitInt = new Integer[6];
        double FrE;
        int[] FE = new int[10];
        int[] baraja = new int[n];
        for (int i = 0; i < 10; i++) {
            FE[i] = 0;
        }
        DecimalFormat df = new DecimalFormat("#.00000");//lomit the number of decimals

        for (int i = 0; i < n; i++) {
            number = serie[i] / Math.pow(10, nCards);
            numbersFloat[i] = number;
            print += df.format(number) + "\n";
            str = df.format(number);
            textAreaData.setText(print);
            
            char[] digits = str.toString().toCharArray();
            String numStr = Character.toString(digits[i + 1]);
            int num = Integer.parseInt(numStr);
            digitInt[i] = num;
            
            for (int j = 0; j <digits.length; j++) {

                for (int k = j + 1; k < digits.length; k++) {

                    if (digits[j] == digits[k]) {
                        System.out.println("k  "+digits[k]);
                        if (digits[k] == 0) {
                            FE[0]++;
                            //n0++;
                        } else if (digits[k] == 1) {
                            //n1++;
                            FE[1]++;

                        } else if (digits[k] == 2) {
                            //n2++;
                            FE[2]++;

                        } else if (digits[k] == 3) {
                            //n3++;
                            FE[3]++;

                        } else if (digits[k] == 4) {
                            //n4++;
                            FE[4]++;

                        } else if (digits[k] == 5) {
                            //n5++;
                            FE[5]++;

                        } else if (digits[k] == 6) {
                            //n6++;
                            FE[6]++;

                        } else if (digits[k] == 7) {
//                          n7++;
                            FE[7]++;

                        } else if (digits[k] == 8) {
                            //n8++;
                            FE[8]++;

                        } else if (digits[k] == 9) {
                            //n9++;
                            FE[9]++;

                        }

                    }
                }

            }

            //System.out.println(i+" n0: "+n0+" n1: "+n1+" n2: "+n2+" n3: "+n3+" n4: "+n4+" n5: "+n5+" n6: "+n6+" n7: "+n7+" n8: "+n8+" n9: "+n9);
            int checker = 0;
            for (int k = 0; k < 9; k++) {
                if (FE[k] == 1) {
                    checker++;
                } else if (FE[k] == 3) {
                    checker = 3;
                }
            }

            if (checker == 0) {
                baraja[i] = 1;
            } else if (checker == 1) {
                baraja[i] = 2;
            } else if (checker == 2) {
                baraja[i] = 3;
            } else if (checker == 3) {
                baraja[i] = 4;
            } else if (checker == 6) {
                baraja[i] = 5;
            }

            for (int z = 0; z < 10; z++) {
                FE[z] = 0;
            System.out.println("[" + i + "]" + baraja[i]);
            PrintTotal+= "[" + i + "]" + baraja[i]+"\n";
            }
             textAreaFE.setText(PrintTotal);
        }

    }

//End methods
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITestPoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITestPoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITestPoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITestPoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITestPoker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPoker;
    private javax.swing.JComboBox<String> cbPPoker;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JTextArea textAreaData;
    private javax.swing.JTextArea textAreaFE;
    private javax.swing.JTextArea textAreaSalidaPoker;
    private javax.swing.JTextField txtDPoker;
    private javax.swing.JTextField txtSemillaPoker;
    private javax.swing.JTextField txtTPoker;
    // End of variables declaration//GEN-END:variables
}
