/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conguencial_multiplicativo;

/**
 *
 * @author jonathan
 */
public class pruebasCorridas extends javax.swing.JFrame {

    /**
     * Creates new form pruebasCorridas
     */
    public pruebasCorridas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSerie = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaCorrida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        txtN1 = new javax.swing.JTextField();
        txtZo = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        txtXr = new javax.swing.JTextField();
        txtSr = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        btnRun = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaSerie.setColumns(20);
        textAreaSerie.setRows(5);
        textAreaSerie.setDragEnabled(true);
        textAreaSerie.setOpaque(false);
        jScrollPane1.setViewportView(textAreaSerie);

        txtAreaCorrida.setColumns(20);
        txtAreaCorrida.setRows(5);
        txtAreaCorrida.setDragEnabled(true);
        txtAreaCorrida.setOpaque(false);
        jScrollPane2.setViewportView(txtAreaCorrida);

        jLabel1.setText("Serie");

        jLabel2.setText("Valor de corridas");

        jLabel3.setText("n1=");

        jLabel4.setText("n2=");

        jLabel5.setText("R=");

        jLabel6.setText("Xr=");

        jLabel7.setText("Sr=");

        jLabel8.setText("H = ");

        jLabel9.setText("Zo = ");

        lblResult.setText("Conclusión");

        txtN1.setEnabled(false);
        txtN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1ActionPerformed(evt);
            }
        });

        txtZo.setEnabled(false);

        txtN2.setEnabled(false);

        txtR.setEnabled(false);

        txtXr.setEnabled(false);
        txtXr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXrActionPerformed(evt);
            }
        });

        txtSr.setEnabled(false);

        txtH.setEnabled(false);

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        jLabel10.setText("Prueba de corridas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtN1)
                            .addComponent(txtN2)
                            .addComponent(txtR)
                            .addComponent(txtXr)
                            .addComponent(txtZo)
                            .addComponent(txtH)
                            .addComponent(txtSr, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtXr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtSr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtZo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1ActionPerformed

    private void txtXrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXrActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        Double[] serie = serie();
        String values = "";//Sirve para almacenoar los valores convertidos de D a S
        //recorre la serie 
        for (int i = 0; i < serie.length; i++) {
            values += serie[i] + "\n";
        }
        textAreaSerie.setText(values);//print ot series

        String binaries = "";
        int[] binary = new int[100];
        for (int i = 0; i < serie.length; i++) {
            if (serie[i] > 0.5) {
                binary[i] = 1;
                binaries += binary[i] + "\n";
                System.out.println("  t2   " + binaries + "\6");
            } else {
                binary[i] = 0;
                binaries += binary[i] + "\n";
            }
        }
        txtAreaCorrida.setText(binaries);//presenta la lista, resultad de la comprobacion de la serie
        //calculate n1, n2 and R
        int n1 = 0;
        int n2 = 0;
        int comparison = 2;
        int runing = 0;
        for (int i = 0; i < binary.length; i++) {
            if (binary[i] != comparison) {
                runing++;
                comparison = binary[i];
            }
        }
        txtR.setText("numero de corrida R: " + runing);
        for (int i = 0; i < binary.length; i++) {
            if (binary[i] == 0) {
                n1++;
            } else {
                n2++;
            }
        }
 
        txtN1.setText("n1: " + n1);
        txtN2.setText("n2: " + n2);
        //End calculate n1 and n2
        //Xr
        double num1 = (double) n1;
        double num2 = (double) n2;
        double promedio = ((2 * num1 * num2) / (num1 + num2)) + 1;
        txtXr.setText(" " + promedio);
        //End Xr
        //Sr
        double desviacion = Math.sqrt(((2 * num1 * num2) * ((2 * num1 * num2) - num1 - num2)) / ((Math.pow((num1 + num2), 2)) * (num1 + num2 - 1)));
        txtSr.setText("" + desviacion);
        //End Sr
        //H
        double H = 0;

        if (runing < promedio) {
            H = +0.5;
        } else {
            H = -0.5;
        }
        txtH.setText("" + H);
        //End H
        //Z
        double z = 0;
        z = (runing + H - promedio) / (desviacion);
        txtZo.setText("" + z);
        //End Z
        //varlidadcion de l auniformidad  de la serie
        if (z > -2.58 && z < 2.58) {
            lblResult.setText("EL valor de Z se encuentra bajo el nivel de aceptacion, equivalente a 2.58: " + z);
        } else {
            lblResult.setText("El valor Z se encuentra sobre el nivel de aceptacion, equivalente a 2.58:" + z);

        }
    }
    //method

    public Double[] serie() {
        Double[] serie = new Double[100];
        serie[0] = 0.03991;
        serie[1] = 0.38555;
        serie[2] = 0.17546;
        serie[3] = 0.32643;
        serie[4] = 0.69572;
        serie[5] = 0.24122;
        serie[6] = 0.61196;
        serie[7] = 0.30532;
        serie[8] = 0.03788;
        serie[9] = 0.48228;
        serie[10] = 0.88618;
        serie[11] = 0.71299;
        serie[12] = 0.27954;
        serie[13] = 0.80863;
        serie[14] = 0.33564;
        serie[15] = 0.90899;
        serie[16] = 0.78038;
        serie[17] = 0.55986;
        serie[18] = 0.87539;
        serie[19] = 0.16818;
        serie[20] = 0.10461;
        serie[21] = 0.95554;
        serie[22] = 0.73704;
        serie[23] = 0.52861;
        serie[24] = 0.68777;
        serie[25] = 0.66591;
        serie[26] = 0.30231;
        serie[27] = 0.21704;
        serie[28] = 0.97599;
        serie[29] = 0.63379;
        serie[30] = 0.19161;
        serie[31] = 0.23853;
        serie[32] = 0.58909;
        serie[33] = 0.00514;
        serie[34] = 0.60780;
        serie[35] = 0.75754;
        serie[36] = 0.70267;
        serie[37] = 0.66485;
        serie[38] = 0.08823;
        serie[39] = 0.60311;
        serie[40] = 0.93716;
        serie[41] = 0.32886;
        serie[42] = 0.92052;
        serie[43] = 0.95819;
        serie[44] = 0.39510;
        serie[45] = 0.27699;
        serie[46] = 0.92962;
        serie[47] = 0.10274;
        serie[48] = 0.75867;
        serie[49] = 0.85783;
        serie[50] = 0.41290;
        serie[51] = 0.05870;
        serie[52] = 0.82444;
        serie[53] = 0.20247;
        serie[54] = 0.48460;
        serie[55] = 0.60833;
        serie[56] = 0.43529;
        serie[57] = 0.88722;
        serie[58] = 0.94813;
        serie[59] = 0.74457;
        serie[60] = 0.16894;
        serie[61] = 0.59780;
        serie[62] = 0.46215;
        serie[63] = 0.06831;
        serie[64] = 0.35905;
        serie[65] = 0.06494;
        serie[66] = 0.61773;
        serie[67] = 0.12202;
        serie[68] = 0.20717;
        serie[69] = 0.47619;
        serie[70] = 0.63312;
        serie[71] = 0.01119;
        serie[72] = 0.99005;
        serie[73] = 0.81759;
        serie[74] = 0.85558;
        serie[75] = 0.25983;
        serie[76] = 0.06318;
        serie[77] = 0.56736;
        serie[78] = 0.31900;
        serie[79] = 0.90561;
        serie[80] = 0.98953;
        serie[81] = 0.09958;
        serie[82] = 0.15917;
        serie[83] = 0.19640;
        serie[84] = 0.85244;
        serie[85] = 0.03152;
        serie[86] = 0.22109;
        serie[87] = 0.94205;
        serie[88] = 0.82037;
        serie[89] = 0.87481;
        serie[90] = 0.71857;
        serie[91] = 0.92784;
        serie[92] = 0.04921;
        serie[93] = 0.45197;
        serie[94] = 0.15191;
        serie[95] = 0.01291;
        serie[96] = 0.38384;
        serie[97] = 0.66164;
        serie[98] = 0.54155;
        serie[99] = 0.72848;

        return serie;

        //end methos

    }//GEN-LAST:event_btnRunActionPerformed

    //end methos
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebasCorridas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebasCorridas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebasCorridas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebasCorridas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebasCorridas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextArea textAreaSerie;
    private javax.swing.JTextArea txtAreaCorrida;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtSr;
    private javax.swing.JTextField txtXr;
    private javax.swing.JTextField txtZo;
    // End of variables declaration//GEN-END:variables
}
