package conguencial_multiplicativo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jonathan
 */
public class vista extends javax.swing.JFrame {

    double prom = 0;
    double prom2 = 0;
    double z;
    double divisor = Math.sqrt(0.0833333333);
    int modulo = 0;

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxSemilla = new javax.swing.JComboBox<>();
        txtConsM = new javax.swing.JTextField();
        txtModulo = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        cajaSalida = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Semilla");

        jLabel2.setText("Constante multiplicativa");

        jLabel3.setText("Modulo");

        jLabel4.setText("Congruencial multiplicativo");

        cbxSemilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "7", "11", "13", "17", "19", "23", "29", "31", "37", "41", "43", "47", "53", "59", "61", "67", "71", "73", "79", "83", "89", "97" }));
        cbxSemilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSemillaActionPerformed(evt);
            }
        });

        txtConsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsMActionPerformed(evt);
            }
        });

        txtModulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModuloActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cajaSalida))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModulo)
                            .addComponent(cbxSemilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsM)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(txtConsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(cajaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSemillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSemillaActionPerformed

    }//GEN-LAST:event_cbxSemillaActionPerformed

    private void txtModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModuloActionPerformed

    private void txtConsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsMActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Double seeb = Double.parseDouble((String)cbxSemilla.getSelectedItem());
        int cMultiplicativa = Integer.parseInt(txtConsM.getText().toString());
        modulo = Integer.parseInt(txtModulo.getText().toString());
        int semilla = seeb.intValue();
        int t = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor de t"));
        int a = (200*t) - semilla;
        int d = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor de d"));
        int aux = 0;
        double[] arregl = new double[1];
        aux = modulo;
        int periodo;
        double suma = 0;
        int resta;
        double min = 0;
        ArrayList<Integer> miArrayList = new ArrayList<Integer>();
        double div = 0;
        double residuo = 0;
        int aleatorio = 0;
        double select = 0;
        if (d >= 5) {
            resta = d - 2;

            periodo = (int) (5 * (Math.pow(modulo, resta)));
            for (int i = 0; i < periodo; i++) {
                residuo = (a * seeb) % modulo;
                seeb = residuo;
            }
            prom2 = prom / periodo;

            z = (prom2 - 0.5) * Math.sqrt(100) / divisor;

            if (z < 1.96) {
                JOptionPane.showMessageDialog(null, "No se puede rechazar la hipotesis de que estos numeros pseudoaleatorios tienen una media de 0.5");
            } else {
                JOptionPane.showMessageDialog(null, " Se rechaza la hipotesis de que estos numeros pseudoaleatorios tienen una media de 0.5");
            }
        }

        if (d < 5) {
            for (int i = 1; i <= modulo; i++) {
                for (int j = modulo; j > 0; j--) {
                    double rai = Math.sqrt(i);
                    double raj = Math.sqrt(j);
                    if (Par(rai) == true && Par(raj) == true) {
                        // System.out.println(rai + "   " + raj);

                        if ((Math.pow(rai, 2)) * (Math.pow(raj, 2)) == aux || (Math.pow(rai, 2)) + (Math.pow(raj, 2)) == aux) {

                            if (rai != 1 && raj != 1) {
                                min = mcm(rai, raj);
                                System.out.println(min);
                                periodo = (int) min;
                                miArrayList.add(periodo);
                            }
                        }

                    }
                }
            }

            aleatorio = (int) Math.floor(Math.random() * (miArrayList.size()));
            String resultado = "";
            for (int i = 0; i < miArrayList.get(aleatorio); i++) {

                residuo = (a * seeb) % modulo;

                cajaSalida.setText(" " + residuo);

                resultado = resultado + (i + " | " + residuo + "\n");
                seeb = residuo;
            }
            prom2 = prom / miArrayList.get(aleatorio);
            JOptionPane.showMessageDialog(null, "n  " + "  X\n" + resultado);
             cajaSalida.setText(resultado);

            z = (prom2 - 0.5) * Math.sqrt(100) / divisor;

            if (z < 1.96) {
               JOptionPane.showMessageDialog(null, "No se puede rechazar la hipótesis de que estos numeros pseudoaleatorios tienen una media de 0.5");
            } else {
                JOptionPane.showMessageDialog(null, " Se rechaza la hipótesis de que estos numeros pseudoaleatorios tienen una media de 0.5");
            }
        
        }
        ///
        /*  int i, numero;
        double numero2;

        int[] resEntero = new int[100];
        double[] resDecimal = new double[100];
        for (i = 1; i <= 20; i++) {
            numero = (cMultiplicativa * seeb) % modulo;
            numero2 = (double) numero / (double) (modulo - 1);
            resEntero[i] = numero;
            resDecimal[i] = numero2;
            //System.out.printf("%d. %d (%.4f)\n", i, numero, numero2);
            seeb = numero;
            i++;
        }
        for (int j = 0; j <= resDecimal.length; j++) {

            System.out.println(resEntero[j] + "/" + resDecimal[j]);
        }*/
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
//metodos
    public int MCM(int mod) {
        //descomopocicion de un numero
        //divicion
        int n1 = 1;
        int n2 = 0;
        int dividendo = mod;
        int divisor = 2;
        int cociente = 0;
        int residuo = 0;
        //mmcm
        int mcm = 0;
        int min = 0;
        if (residuo == 0) {
            cociente = dividendo / divisor;
            residuo = dividendo % divisor;
            if (residuo == residuo) {
                n1 = divisor * n1;
            } else {

            }
        } else if (residuo != 0) {
            divisor++;
        }

        return mcm;
    }

    public static boolean Par(double num1) {
        if (num1 % 1 == 0) {
            return true;
        } else {
            return false;
        }
    }

    public static boolean impar(double num2) {
        if (num2 % 2 == 0) {
            return false;
        } else {
            return true;
        }
    }

    public static boolean rltvPrimo(int a, int b) {

        int max;
        if (a >= b) {
            max = a;
        } else {
            max = b;
        }
        int count = 0;
        for (int i = 2; i <= max; i++) {
            if (a % i == 0 && b % i == 0) {
                count++;
            }
        }
        if (count == 0) {
            return true;
        } else {
            return false;
        }
    }

    static double mcm(double a, double b) {
        double multiplo;

        if (a > b) {
            multiplo = a;
        } else {
            multiplo = b;
        }

        while (multiplo % a != 0 || multiplo % b != 0) {
            multiplo++;
        }
        return multiplo;
    }

    //fin metodos
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField cajaSalida;
    private javax.swing.JComboBox<String> cbxSemilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtConsM;
    private javax.swing.JTextField txtModulo;
    // End of variables declaration//GEN-END:variables
}
